HaikuPorter/Options.py
HaikuPorter/Source.py

This PR adds an option to ignore creating a git repo. This drastically reduces the time required to download & prepare packages.
It has a built in safety feature which will make the program create a repo if patches exist. This is used to prevent any issues with patches attempting to be applied when no git repo is available.

Add option to not create a git repo

---

HaikuPorter/Main.py
HaikuPorter/Repository.py

This closes #69 and #47.
Turns out the most active version of each port was being used including the port the user would like to build. This causes the wrong dependency file to be generated.

Fix support for building older versions of packages

---

HaikuPorter/Main.py
HaikuPorter/Utils.py

This closes #68.
Turns out the _checkFormatVersions() was being called before _updatePortsTree(), which would cause an issue if the haikuports repo was not installed. In addition, the URLs to the repos were not correct and threw errors.

Fix error where --get doesn't work

---

HaikuPorter/ShellScriptlets.py

* **`fixLibtoolArchives`** assumed each reference to an external **`lib*.la`** file was followed by a white space or by an end of line, but this is not true for the last **`lib*.la`** of the line because of the closing single quote. The basename of the libtool file was therefore not detected correctly, so the corresponding package-links directory could not be found for the last **`lib*.la`** of the **`dependency_libs`** parameter in the packages' libtool files. This is now fixed.
* Improve the substitution by using the dirnames of the libtool file instead of its full path. This allows to also fix any paths passed with -L.
_Reminder:_ The call to the **`fixLibtoolArchives`** helper function takes no arguments and should happen **before** the **`packageEntries devel ...`**

ShellScriptlets.py: fix corner-case bug in fixLibtoolArchives. (WIP)

---

HaikuPorter/Utils.py

* use MyTarInfo also for piped inputs.
* adjust tarinfo.linkname to be relative to the entry parent directory:
at least the archives I tried, linkname is a full path to be resolved from
the archive base directory.

Utils: handle hardlinks in xz archives.

---

HaikuPorter/Package.py

* app-vim/cream is an example, it would before this change be stable.

Package: the any architecture can also be broken.

---

HaikuPorter/Repository.py

This will make haikuporter use **`repository-<buildArchitecture>`** instead of just **`repository`**, which was being reset and populated again everytime hp detected it was running on another arch.

repository path: Append '-' + buildPlatform.targetArchitecture

---

HaikuPorter/Configuration.py
HaikuPorter/Main.py
HaikuPorter/Repository.py

to allow relocation/specification of the repository directory.
~~Of course, this change is neutral if you don't set that parameter.~~
While at it, drop the suffix ('-' + $targetArchitecture) that was added to the default path for the repository directory, in the previous commit. The default path is therefore restored:
$OUTPUT_DIRECTORY/repository

Configuration: new optional REPOSITORY_PATH parameter

---

HaikuPorter/ShellScriptlets.py

This fixes `packageEntries()` for package with glob characters in their name, for example `crypto++`

ShellScriptlets: add quote

---

HaikuPorter/Options.py

Also, change -j default value from 1 to the CPU count.
Fixes #1039

HaikuPorter: use cpu_count() as default value for -j

---

HaikuPorter/Port.py

Before the introduction of the `TEST_REQUIRES` variable, the `TEST` phase depended only on `BUILD_REQUIRES`. After `TEST_REQUIRES` was introduced, the `TEST` phase started to _also_ depend on `REQUIRES` and `TEST_REQUIRES`. The downside of making the `TEST` phase depend on `REQUIRES` is that, in some cases, haikuporter cannot satisfy such a dependency. That's because haikuporter considers the `REQUIRES` of the base package and _every_ subpackage. This means that if any subpackage has a dependency that cannot be met then `--test` becomes useless for that package.
The fix for this issue is easy:  make the `TEST` phase depend _only_ on `BUILD_REQUIRES` and `TEST_REQUIRES`.
This change does not break anything. It only means that, from now on, we will have to consider adding …

Do not make the TEST phase depend on REQUIRES.

---

HaikuPorter/Package.py

This reverts 6eb039eb2da57667a5c2db993705933fea1182ef.
This is particularly annoying for perl and python packages which should be
depending on a version of perl or python.

Update requirements for packages of type any.

---

HaikuPorter/DependencyResolver.py

pkgman doesn't seem to be able to process this: 'cmd:lrelease >= 5', but
it can if you remove all the spaces: 'cmd:lrelease>=5'.
Not sure if it's a pkgman bug.
Fixes #188

DependencyResolver: remove whitespace before passing to pkgman

---

HaikuPorter/Repository.py

This function has two loops which iterate over the items in a dictionary and
then conditionally remove from that dictionary. dict.items() returns an
iterator and not a copy of the (key, value) pairs it contains, so it isn't
safe to remove from this loop.
This makes a copy of the items by converting the iterator to a tuple.
Fixes #199.

python3: errors from mutating collections while iterating

---

HaikuPorter/Policy.py

This is a common mistake, like when the package name is different than the provided command, it just happened to me again on hteditor.

Policy: check if a package provides itself

---

HaikuPorter/Main.py

- Fixes https://github.com/haikuports/haikuporter/issues/215
- raw_input() has been deprecated and replaced with input()

python3: Use input instead of raw_input

---

HaikuPorter/Policy.py

* Also checks for versioned libraries, as these satisfy the
binary requirements.
* Fixes policy warnings for packages that don't provided
non-versioned shared libraries (e.g. krb5)

Policy: improve needed library check.

---

HaikuPorter/BuildPlatform.py

Latest change in haikuporter introduces cmd:which as a prerequirement for shell scriptlets.
When I try to do bootstrap build, now I get the following error message:
`scriptlet-prerequires "cmd:which" of package "gcc_bootstrap-8.3.0_2019_05_24" could not be resolved`
This proposed change adds cmd:which to implicitBuildHostProvides when cross-building.

BuildPlatform: assume 'which' command is available on Unix build host

---

HaikuPorter/BuildPlatform.py

This seems to be needed to be able to bootstrap for arm.
Before: bootstrap fails with dependency issues
```
build-prerequires "cmd:git" of package "mesa_devel-21.3.7" could not be resolved
build-requires "devel:libgl" of package "libsdl2_devel-2.0.20" could not be resolved
build-requires "devel:libsdl2" of package "tk_devel-8.6.10" could not be resolved
build-requires "devel:libtk8.6" of package "python3-3.7.12" could not be resolved
build-prerequires "cmd:python3" of package "freetype-2.11.1" could not be resolved
build-requires "freetype" of package "meta_portsfile-1" could not be resolved
```
After: bootstrap is able to reach at least the stage when it's preparing the "rigged" source packages. (haven't finished yet, I hope that it will be successful)

BuildPlatform: assume git is available on Unix build host

---

HaikuPorter/ShellScriptlets.py

Variables containing single quotes cause problems when imported by Bash.
This patch fixes the issue by replacing `'` in these variables with `'\''`.
Fixes #145.

ShellScriptlets: Escape single quotes in variables.

---

HaikuPorter/Port.py

Seems to work better than using absolute paths everywhere.
I tried it with wireshark and tenacity, I get successful builds without any patching on the `CMakeLists.txt` files.

use relative paths in cmakeDirArgs

---

HaikuPorter/Port.py

so that the PR lint workflow will go red if this happens

make unreferenced patches an error

---

HaikuPorter/ShellScriptlets.py

Remove the boot dir from the chroot, even if $buildOK is false. This avoids that annoying "waiting for package to be activated".
Deleting just "boot/system/packages/administrative/activated_packages" might be enough, but... this works well for me, and it's already how it's done if $buildOK is true.

Workaround for issue #207.

---

README.md
buildmaster/backend/README.md
buildmaster/backend/assets/bin/buildmaster
buildmaster/backend/assets/bin/createbuilder
buildmaster/backend/assets/bin/missing_ports.sh
buildmaster/backend/assets/loop
doc/haikuporter_bash_completion
haikuports-sample.conf
haikuports.conf

While making the package modern I've changed filename of `haikuporter` to `haikuporter.py`. I didn't notice that this script is included in other places and is actively used by the scripts. I've changed all occurrences of script file name that is appearing in other files.

[FIX] Fix problems caused by changing script file name

---

HaikuPorter/BuildPlatform.py

one more for the bootstrap build... haikuporter itself is a python3 script so it's pretty much straightforward to assume that the build host has python3 available

BuildPlatform: assume python3 is available on Unix build host

---

HaikuPorter/BuildMaster.py
HaikuPorter/BuildPlatform.py
HaikuPorter/Builders/LocalBuilder.py
HaikuPorter/Builders/MockBuilder.py
HaikuPorter/Builders/RemoteBuilderSSH.py
HaikuPorter/ConfigParser.py
HaikuPorter/Configuration.py
HaikuPorter/DependencyAnalyzer.py
HaikuPorter/DependencyResolver.py
HaikuPorter/Display.py
HaikuPorter/Main.py
HaikuPorter/Options.py
HaikuPorter/Package.py
HaikuPorter/PackageInfo.py
HaikuPorter/PackageRepository.py
HaikuPorter/Policy.py
HaikuPorter/Port.py
HaikuPorter/ProvidesManager.py
HaikuPorter/RecipeAttributes.py
HaikuPorter/ReporterJson.py
HaikuPorter/ReporterMongo.py
HaikuPorter/Repository.py
HaikuPorter/RequiresUpdater.py
HaikuPorter/Source.py
HaikuPorter/SourceFetcher.py
HaikuPorter/Utils.py

- Import statements sorted with `isort` command. 
- `MockBuilder.py` fixed:
- Fixed missing closing bracket at the end of the file
- Fixed missing import
- Removed unnecessary (correct my if I'm wrong) import statement `from __future__ import absolute_import` from `ConfigParser.py`. 
**Open point**
Maybe someone will know - what was the reason for using `absolute_import` in `ConfigParser.py`? 
Please remember to tick the checkbox for squashing commits before merging PR to master (I forgot to do that and I don't have a possibility to change it after creating the PR).

Import statements sorted with isort and fixed MockBuilder.py

---

.github/workflows/python_package.yml
HaikuPorter/BuildMaster.py
HaikuPorter/Builders/Builder.py
HaikuPorter/Builders/LocalBuilder.py
HaikuPorter/Builders/RemoteBuilderSSH.py
tests/Builders/test_builder.py
tests/requirements.txt
tox.ini

Things changed:
- Changed name from `_BuilderState` to `BuilderState`.
- Removed `object` inheritance (it's unnecessary for python3)
- Added unit tests for `BuilderState`
- Added tox-based CI

Small refactor of Builders/Builder.py

---

HaikuPorter/Source.py

This makes sure that the patch output is consistent, even if users use different values for that option.
`haikuporter -e` is called by developers and its output ends up in the haikuports repository, so it should be as consistent as possible to avoid unnecessary noise.
Other commands either don't produce any visible output or are run on the buildmaster systems where there is a defined environment, so it isn't necessary to define the git config explicitly.
If there are other options which influence the output of `format-patch`, they should also be set explicitly.

extractPatchset: add git config core.abbrev=auto to format-patch call

---

HaikuPorter/Source.py

Rationale: when the git config setting `tag.gpgSign=true` is used, this implies the `-s` option to `git tag`. This means that git needs a message for the tag. Because no message is given, git invokes an editor, which doesn't work when running non-interactively.
We don't need signed tags in a git repo created by HaikuPorter, so the easiest solution is to pass `--no-sign` to `git tag` calls.

Don't sign git tags

---

HaikuPorter/Port.py
HaikuPorter/Source.py

We could have commented out lines in PROVIDES, and REQUIRES, but not in PATCHES, as those lines weren't being filtered out, ending on "file not found" errors further down.

Support commented out lines in the PATCHES section.

---

HaikuPorter/BuildMaster.py
HaikuPorter/Builders/LocalBuilder.py
HaikuPorter/Builders/RemoteBuilderSSH.py
HaikuPorter/Main.py
HaikuPorter/Options.py
HaikuPorter/Package.py
HaikuPorter/PackageInfo.py
HaikuPorter/PackageRepository.py
HaikuPorter/Port.py
HaikuPorter/StorageBackendS3.py
buildmaster/backend/Dockerfile
buildmaster/backend/README.md
buildmaster/backend/assets/bin/buildmaster
buildmaster/backend/assets/bin/createbuilder
buildmaster/backend/assets/bin/update_build_packages
buildmaster/backend/assets/bootstrap
buildmaster/backend/assets/loop
buildmaster/frontend/Dockerfile
buildmaster/frontend/configs/buildmaster-frontend.conf
pyproject.toml
storage-backend-sample.json

* Adds object storage based backing for the package repository (S3 API only for now)
* Reduces the number of volumes that are used to ease deployment
* Fixes constant reuploads of system-packages to builders
* Other minor fixes and cleanups
After deployment this should fix #258.

Implement S3 Object Storage for Package Repositories

---

HaikuPorter/Port.py

haikuporter always generated package_x86.patchset files.
Now it should always use the basename so you don't have to manually rename the patchset files

don't add the secondaryArchSuffix on patchset export

---

HaikuPorter/Package.py
HaikuPorter/Policy.py

instead of ignoring it.
* fixes #278

Policy: automatically add libstdc++ in requires

---

HaikuPorter/Source.py
HaikuPorter/SourceFetcher.py

* checksums for git commits or git tags can then be enabled, example: git+https://github.com/HaikuArchives/StreamRadio.git#tag=1.0.0 or #commit=$srcGitRev
* this works by hashing the checkout content. inspired by the same feature in pacman from Arch.

Source/SourceFetcher: let the fetcher compute the checksum

---

generic/generic_perl-1.23.recipe
generic/generic_perl_module_build-1.23.recipe
generic/generic_perl_xs-1.23.recipe

I also added some explaining comments to the main recipe.

add generic perl recipes

---

HaikuPorter/Package.py
HaikuPorter/Policy.py
HaikuPorter/Port.py
HaikuPorter/RecipeAttributes.py

This is analoguous to post-install scripts.
Defines a new recipe attribute PRE_UNINSTALL_SCRIPTS and new directory variables $preUninstallDir and $relativePreUninstallDir.
Fixes #306.

Add support for pre-uninstall scripts

---

HaikuPorter/Main.py

Had this small patch lying around for too long.
Makes reading/comparing the output `--list-dependencies` easier.

Sort the output of --list-dependencies.

---

HaikuPorter/ShellScriptlets.py

and therefore packageEntries.
Untested because nothing seems to use this currently.

ShellScriptlets: better support for PACKAGE_NAME and PACKAGE_VERSION in getPackagePrefix

---

HaikuPorter/Package.py
HaikuPorter/Port.py
HaikuPorter/ShellScriptlets.py

When determining the architecture of a package, check whether it is "any" before checking the secondary architecture.
To make "any" packages identical to the case when not using a secondary architecture, don't include the secondaryArchSuffix in the package name in this case. This is a breaking change! Any packages using this must update the PROVIDES of the subpackage and should add a REPLACES entry to facilitate upgrades.
Add support for this change to ShellScriptlets getPackagePrefix, which is also used by packageEntries.
Fixes #320.

fix "any" arch subpackages on secondary arch

---

HaikuPorter/Port.py

Otherwise we would need to handle them specially, similar to REVISION, to get directory variables and everything else depending on the prefix right. It would make the implementation much more complex for little to no advantages, when the recipe could just be renamed instead.

disallow PACKAGE_NAME and PACKAGE_VERSION for the main package

---

HaikuPorter/Main.py
HaikuPorter/Options.py
HaikuPorter/Repository.py

i.e. remove the work directories and downloads of old port (versions) which have been removed. A new command line option "--purge-stale-ports" is introduced for this.
To get the sources of ports (and thus which downloads to keep) it must parse all recipes.
Note that this may be a bit destructive if you are switching git branches while working on something!

Repository: add a function to purge stale ports
